workflow: Check for Prettier format in CI action as well.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -16,6 +16,13 @@ jobs:
     - name: "npm run test"
       run: npm run test
 
+    - name: "check for unformatted sources"
+      run: |
+        npm run format:check
+        || (echo "##[error] found unformatted files. please 'npm run format'" \
+                 "and check in all changes" \
+            && exit 1)
+
     - name: "check for uncommitted changes"
       # Ensure no changes, but ignore node_modules dir since dev/fresh ci deps installed.
       run: |
